### ISSUE TITLE
Random seed?

### ISSUE THREAD

**Issue by robinkoehler** [quickwick/stable-diffusion-win-amd-ui#1]
Thank you very much for providing this GUI!

This may be stupid and basic, but I lack the knowledge: how do I coerce this into using a random seed? I've tried "0", "-1" etc without success. Appreciate your time and any reply!

Take care and best wishes, 

Robin

**Comment by quickwick** [comment]
Great idea! Added in [87047ed](https://github.com/quickwick/stable-diffusion-win-amd-ui/commit/87047eda032c1fb6f731f51df19288f5a6e562c3)

**Comment by robinkoehler** [comment]
> Great idea! Added in [87047ed](https://github.com/quickwick/stable-diffusion-win-amd-ui/commit/87047eda032c1fb6f731f51df19288f5a6e562c3)

Amazing!!! Thank you so much
