### ISSUE TITLE
Quality discrepancy between GUI and default install

### ISSUE THREAD

**Issue by robinkoehler** [quickwick/stable-diffusion-win-amd-ui#3]
I am encountering a very strange quality discrepancy between the images produced through the GUI vs the same prompt and seed used in the default install. I have uploaded the pictures and .txt files in this folder:

https://drive.google.com/drive/folders/1mRu6ijwgYRoSmLbJdbM6mUTS189xWCx7?usp=sharing

I doubt this is usual and it seems the AI is running away with the prompt somewhere, or not using the specified number of 50 steps (even though the console and info confirm it is processing 50 iterations). 

Thank you kindly in advance for evaluating this!

Take care and best wishes, Robin

**Comment by cstueckrath** [comment]
seeing this, too. You have to edit lines 31 and 33 to read` (beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", num_train_timesteps=1000, tensor_format="np")` behind the scheduler. This is missing

**Comment by robinkoehler** [comment]
> seeing this, too. You have to edit lines 31 and 33 to read` (beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", num_train_timesteps=1000, tensor_format="np")` behind the scheduler. This is missing

Brilliant, thank you! That fixed LMSDiscrete and PNDM. DDIM however still produces very cursed outputs. Is there a command specifically for DDIM that has to be added or removed there? Much appreciated!

EDIT: I trialled and errored it until I got it working. Line 29 in text2img_ui.py needs to read:

`        scheduler = DDIMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", clip_sample=False, set_alpha_to_one=False, num_train_timesteps=1000, tensor_format="np")`


Line 28 to line 33 complete for copy and paste:

`    if strvar_scheduler.get() == 'DDIM':
        scheduler = DDIMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", clip_sample=False, set_alpha_to_one=False, num_train_timesteps=1000, tensor_format="np")
    elif strvar_scheduler.get() == 'LMSDiscrete':
        scheduler = LMSDiscreteScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", num_train_timesteps=1000, tensor_format="np")
    elif strvar_scheduler.get() == 'PNDM':
        scheduler = PNDMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", skip_prk_steps=True, num_train_timesteps=1000, tensor_format="np")`

**Comment by quickwick** [comment]
Thank you both. I hadn't gotten around to looking into the scheduler options yet. Updated to @robinkoehler suggested settings in https://github.com/quickwick/stable-diffusion-win-amd-ui/commit/8fe8ab63be3955c59347b5d17a242823c905b194
